query mostRecentPastContest($pageNo: Int, $numPerPage: Int) {
  pastContests(pageNo: $pageNo, numPerPage: $numPerPage) {
    data {
      title
      titleSlug
      startTime
      questions {
        title
        titleSlug
        __typename
      }
      __typename
    }
    __typename
  }
}